name: 'Prompt Story'
description: 'Analyze and display LLM session transcripts from git-prompt-story notes'
author: 'QuesmaOrg'
branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: true
    default: ${{ github.token }}

  fail-if-no-notes:
    description: 'Fail the action if no prompt-story notes found'
    required: false
    default: 'false'

  version:
    description: 'Version of git-prompt-story to use (default: latest)'
    required: false
    default: 'latest'

outputs:
  commits-analyzed:
    description: 'Number of commits analyzed'
    value: ${{ steps.analyze.outputs.commits-analyzed }}

  commits-with-notes:
    description: 'Number of commits with prompt-story notes'
    value: ${{ steps.analyze.outputs.commits-with-notes }}

  should-post-comment:
    description: 'Whether a PR comment should be posted'
    value: ${{ steps.analyze.outputs.should-post-comment }}

  comment-id:
    description: 'ID of the PR comment created'
    value: ${{ steps.comment.outputs.comment-id }}

runs:
  using: 'composite'
  steps:
    - name: Fetch git notes
      shell: bash
      run: ${{ github.action_path }}/scripts/fetch-notes.sh

    - name: Download git-prompt-story
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/scripts/download-binary.sh

    - name: Analyze commits
      id: analyze
      shell: bash
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        FAIL_IF_NO_NOTES: ${{ inputs.fail-if-no-notes }}
      run: ${{ github.action_path }}/scripts/analyze.sh

    - name: Post PR comment
      id: comment
      if: steps.analyze.outputs.should-post-comment == 'true'
      uses: actions/github-script@v7
      env:
        NOTES_MISSING: ${{ steps.analyze.outputs.notes-missing }}
        COMMITS_MISSING_NOTES: ${{ steps.analyze.outputs.commits-missing-notes }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');

          let body;
          const notesMissing = process.env.NOTES_MISSING === 'true';
          const commitsMissingNotes = process.env.COMMITS_MISSING_NOTES || '0';

          if (notesMissing && !fs.existsSync('./prompt-story-summary.md')) {
            // Commits have markers but notes are missing - warn user
            body = `## ⚠️ Prompt Story Notes Not Found

          This PR has ${commitsMissingNotes} commit(s) with \`Prompt-Story:\` markers, but the notes could not be fetched.

          **Did you forget to push your notes?**

          \`\`\`bash
          git push origin refs/notes/prompt-story
          \`\`\`

          Or push all refs including notes:
          \`\`\`bash
          git push --all && git push origin refs/notes/prompt-story
          \`\`\`

          ---
          *Generated by [git-prompt-story](https://github.com/QuesmaOrg/git-prompt-story)*`;
          } else {
            // Read the generated markdown summary
            body = fs.readFileSync('./prompt-story-summary.md', 'utf8');
          }

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('git-prompt-story')
          );

          if (botComment) {
            // Update existing comment
            const { data: updated } = await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body,
            });
            core.setOutput('comment-id', updated.id);
          } else {
            // Create new comment
            const { data: created } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body,
            });
            core.setOutput('comment-id', created.id);
          }
