name: 'Prompt Story'
description: 'Analyze and display LLM session transcripts from git-prompt-story notes'
author: 'QuesmaOrg'
branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for PR comments and Pages deployment'
    required: true
    default: ${{ github.token }}

  comment:
    description: 'Post a summary comment on the PR'
    required: false
    default: 'true'

  deploy-pages:
    description: 'Deploy full transcripts to GitHub Pages'
    required: false
    default: 'true'

  pages-branch:
    description: 'Branch for GitHub Pages deployment'
    required: false
    default: 'gh-pages'

  summary-mode:
    description: 'Summary mode: brief or full'
    required: false
    default: 'brief'

  fail-if-no-notes:
    description: 'Fail the action if no prompt-story notes found'
    required: false
    default: 'false'

  version:
    description: 'Version of git-prompt-story to use (default: latest)'
    required: false
    default: 'latest'

outputs:
  commits-analyzed:
    description: 'Number of commits analyzed'
    value: ${{ steps.analyze.outputs.commits-analyzed }}

  commits-with-notes:
    description: 'Number of commits with prompt-story notes'
    value: ${{ steps.analyze.outputs.commits-with-notes }}

  pages-url:
    description: 'URL to the deployed GitHub Pages transcript'
    value: ${{ steps.deploy.outputs.pages-url }}

  comment-id:
    description: 'ID of the PR comment created'
    value: ${{ steps.comment.outputs.comment-id }}

runs:
  using: 'composite'
  steps:
    - name: Fetch git notes
      shell: bash
      run: ${{ github.action_path }}/scripts/fetch-notes.sh

    - name: Download git-prompt-story
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/scripts/download-binary.sh

    - name: Analyze commits
      id: analyze
      shell: bash
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        SUMMARY_MODE: ${{ inputs.summary-mode }}
        FAIL_IF_NO_NOTES: ${{ inputs.fail-if-no-notes }}
      run: ${{ github.action_path }}/scripts/analyze.sh

    - name: Generate HTML pages
      if: inputs.deploy-pages == 'true'
      shell: bash
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        ./git-prompt-story ci-html "${BASE_SHA}..${HEAD_SHA}" \
          --output-dir="./prompt-story-pages/pr-${PR_NUMBER}" \
          --pr="${PR_NUMBER}"

    - name: Deploy to GitHub Pages
      id: deploy
      if: inputs.deploy-pages == 'true'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ./prompt-story-pages
        destination_dir: ''
        publish_branch: ${{ inputs.pages-branch }}
        keep_files: true

    - name: Set pages URL
      if: inputs.deploy-pages == 'true'
      id: pages-url
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        # Construct GitHub Pages URL
        REPO_OWNER="${GITHUB_REPOSITORY_OWNER}"
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        PAGES_URL="https://${REPO_OWNER}.github.io/${REPO_NAME}/pr-${PR_NUMBER}/"
        echo "pages-url=${PAGES_URL}" >> $GITHUB_OUTPUT

    - name: Post PR comment
      id: comment
      if: inputs.comment == 'true'
      uses: actions/github-script@v7
      env:
        PAGES_URL: ${{ steps.pages-url.outputs.pages-url }}
        DEPLOY_PAGES: ${{ inputs.deploy-pages }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');

          // Read the generated markdown
          let body = fs.readFileSync('./prompt-story-summary.md', 'utf8');

          // Add pages link if deployed
          if (process.env.DEPLOY_PAGES === 'true' && process.env.PAGES_URL) {
            body = body.replace(
              '---\n*Generated by',
              `[View full transcripts](${process.env.PAGES_URL})\n\n---\n*Generated by`
            );
          }

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('## Prompt Story')
          );

          if (botComment) {
            // Update existing comment
            const { data: updated } = await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body,
            });
            core.setOutput('comment-id', updated.id);
          } else {
            // Create new comment
            const { data: created } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body,
            });
            core.setOutput('comment-id', created.id);
          }
