# GoReleaser configuration for git-prompt-story
# Run: goreleaser release --clean
# Or use GitHub Actions with goreleaser-action

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: git-prompt-story
    main: .
    binary: git-prompt-story
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: QuesmaOrg
    name: git-prompt-story
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: git-prompt-story
    homepage: https://github.com/QuesmaOrg/git-prompt-story
    description: "Git commit prompt generator using AI to create meaningful commit messages"
    license: "Apache-2.0"
    repository:
      owner: QuesmaOrg
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "git-prompt-story"
