name: 'Prompt Story with Pages'
description: 'Analyze LLM session transcripts and deploy full transcripts to GitHub Pages'
author: 'QuesmaOrg'
branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for PR comments and Pages deployment'
    required: true
    default: ${{ github.token }}

  pages-branch:
    description: 'Branch for GitHub Pages deployment'
    required: false
    default: 'gh-pages'

  fail-if-no-notes:
    description: 'Fail the action if no prompt-story notes found'
    required: false
    default: 'false'

  version:
    description: 'Version of git-prompt-story to use (default: latest)'
    required: false
    default: 'latest'

outputs:
  commits-analyzed:
    description: 'Number of commits analyzed'
    value: ${{ steps.analyze.outputs.commits-analyzed }}

  commits-with-notes:
    description: 'Number of commits with prompt-story notes'
    value: ${{ steps.analyze.outputs.commits-with-notes }}

  pages-url:
    description: 'URL to the deployed GitHub Pages transcript'
    value: ${{ steps.pages-url.outputs.pages-url }}

  comment-id:
    description: 'ID of the PR comment created'
    value: ${{ steps.comment.outputs.comment-id }}

runs:
  using: 'composite'
  steps:
    - name: Fetch git notes
      shell: bash
      run: ${{ github.action_path }}/../prompt-story/scripts/fetch-notes.sh

    - name: Download git-prompt-story
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: ${{ github.action_path }}/../prompt-story/scripts/download-binary.sh

    - name: Analyze commits
      id: analyze
      shell: bash
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        FAIL_IF_NO_NOTES: ${{ inputs.fail-if-no-notes }}
      run: ${{ github.action_path }}/../prompt-story/scripts/analyze.sh

    - name: Generate HTML pages
      if: steps.analyze.outputs.commits-with-notes != '0'
      shell: bash
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        ./git-prompt-story ci-html "origin/${BASE_REF}..HEAD" \
          --output-dir="./prompt-story-pages/prompt-story/pr-${PR_NUMBER}" \
          --pr="${PR_NUMBER}"

    - name: Deploy to GitHub Pages
      id: deploy
      if: steps.analyze.outputs.commits-with-notes != '0'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ./prompt-story-pages
        destination_dir: ''
        publish_branch: ${{ inputs.pages-branch }}
        keep_files: true

    - name: Set pages URL
      if: steps.analyze.outputs.commits-with-notes != '0'
      id: pages-url
      uses: actions/github-script@v7
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { data: pages } = await github.rest.repos.getPages({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const pagesUrl = pages.html_url + 'prompt-story/pr-' + process.env.PR_NUMBER + '/';
          core.setOutput('pages-url', pagesUrl);

    - name: Post PR comment
      id: comment
      if: steps.analyze.outputs.commits-with-notes != '0'
      uses: actions/github-script@v7
      env:
        PAGES_URL: ${{ steps.pages-url.outputs.pages-url }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');

          // Read the generated markdown
          let body = fs.readFileSync('./prompt-story-summary.md', 'utf8');

          // Add pages link
          if (process.env.PAGES_URL) {
            body = body.replace(
              '---\n*Generated by',
              `[View full transcripts](${process.env.PAGES_URL}) (available while open + 30 days after close)\n\n---\n*Generated by`
            );
          }

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c =>
            c.user.type === 'Bot' &&
            c.body.includes('git-prompt-story')
          );

          if (botComment) {
            // Update existing comment
            const { data: updated } = await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body,
            });
            core.setOutput('comment-id', updated.id);
          } else {
            // Create new comment
            const { data: created } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body,
            });
            core.setOutput('comment-id', created.id);
          }
